[package]
name = "irmaseal-core"
description = "Core library for IRMAseal communication and bytestream operations."
version = "0.1.2"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
keywords = ["ibe", "encryption", "ecc", "no_std"]
homepage = "https://github.com/Wassasin/irmaseal/tree/master/irmaseal-core"
categories = ["cryptography", "no-std"]

[dependencies]
digest = { version = "0.8.1", optional = true }
rand = { version = "0.7.0", optional = true }
aes = { version = "0.4.0", optional = true }
ctr = { version = "0.4.0", optional = true }
hmac = { version = "0.7.1", optional = true }
sha3 = { version = "0.8.2", optional = true }

arrayref = "0.3.5"
arrayvec = { version = "0.4.11", features = ["array-sizes-129-255", "serde-1"] }
subtle = "2.2.1"
serde = { version = "1.0.99", features = ["derive"] }
postcard = "0.5.1"
base64 = "0.10.1"
ibe = "0.1.3"

[features]
default = ["stream"]

stream = ["digest", "rand", "aes", "ctr", "hmac", "sha3"]
